import React, { useState, useEffect } from "react";
import styled from "styled-components";
import { useDispatch } from "react-redux";
import { authActions } from "../../store/auth";
import MailIcon from '../../public/static/svg/input/mail.svg';
import OpenedEyeIcon from '../../public/static/svg/input/opened-eye.svg';
import ClosedEyeIcon from '../../public/static/svg/input/closed_eye.svg';
import palette from "../../styles/palette";
import Button from "../common/button/Button";
import { loginAPI } from "../../lib/api/auth";
import { userActions } from "../../store/user";
import Input from '../common/Input';
import useValidateMode from '../../hooks/useValidateMode';